import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

const flag = z.enum(["on", "off"]).default("on");
const flagOff = z.enum(["on", "off"]).default("off");
const isProd = process.env.NODE_ENV === "production";
const secret = isProd ? z.string().min(16) : z.string().min(1).default("dev-only-insecure-secret");
const maxmindDir = isProd ? z.string().min(1) : z.string().min(1).optional();

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
    AUTH_SECRET: secret,
    AUTH_URL: z.string().url(),
    EMAIL_SERVER_HOST: z.string().min(1).default("localhost"),
    EMAIL_SERVER_PORT: z.coerce.number().int().positive().default(1025),
    EMAIL_SERVER_USER: z.string().optional(),
    EMAIL_SERVER_PASSWORD: z.string().optional(),
    EMAIL_FROM: z.string().min(1).default("noreply@gamblino.local"),
    SENTRY_DSN: z.string().optional(),
    SENTRY_ENVIRONMENT: z.string().default("development"),
    LOG_LEVEL: z.enum(["fatal", "error", "warn", "info", "debug", "trace"]).default("info"),
    FLAG_CRASH: flag,
    FLAG_MINES: flag,
    FLAG_PLINKO: flag,
    FLAG_LOTTERY: flag,
    FLAG_CURRENCY_CREDIT: flag,
    FLAG_CURRENCY_USD: flagOff,
    FLAG_CURRENCY_USDT: flagOff,
    FLAG_CURRENCY_USDC: flagOff,
    FLAG_CURRENCY_BTC: flagOff,
    FLAG_CURRENCY_ETH: flagOff,
    MAXMIND_DB_DIR: maxmindDir,
    UPSTASH_REDIS_REST_URL: z.string().optional(),
    UPSTASH_REDIS_REST_TOKEN: z.string().optional(),
    WS_PORT: z.coerce.number().int().positive().default(3001),
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  },
  client: {
    NEXT_PUBLIC_WS_URL: z.string().url().default("ws://localhost:3001"),
    NEXT_PUBLIC_APP_URL: z.string().url(),
    NEXT_PUBLIC_SENTRY_DSN: z.string().optional(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    AUTH_URL: process.env.AUTH_URL,
    EMAIL_SERVER_HOST: process.env.EMAIL_SERVER_HOST,
    EMAIL_SERVER_PORT: process.env.EMAIL_SERVER_PORT,
    EMAIL_SERVER_USER: process.env.EMAIL_SERVER_USER,
    EMAIL_SERVER_PASSWORD: process.env.EMAIL_SERVER_PASSWORD,
    EMAIL_FROM: process.env.EMAIL_FROM,
    SENTRY_DSN: process.env.SENTRY_DSN,
    SENTRY_ENVIRONMENT: process.env.SENTRY_ENVIRONMENT,
    LOG_LEVEL: process.env.LOG_LEVEL,
    FLAG_CRASH: process.env.FLAG_CRASH,
    FLAG_MINES: process.env.FLAG_MINES,
    FLAG_PLINKO: process.env.FLAG_PLINKO,
    FLAG_LOTTERY: process.env.FLAG_LOTTERY,
    FLAG_CURRENCY_CREDIT: process.env.FLAG_CURRENCY_CREDIT,
    FLAG_CURRENCY_USD: process.env.FLAG_CURRENCY_USD,
    FLAG_CURRENCY_USDT: process.env.FLAG_CURRENCY_USDT,
    FLAG_CURRENCY_USDC: process.env.FLAG_CURRENCY_USDC,
    FLAG_CURRENCY_BTC: process.env.FLAG_CURRENCY_BTC,
    FLAG_CURRENCY_ETH: process.env.FLAG_CURRENCY_ETH,
    MAXMIND_DB_DIR: process.env.MAXMIND_DB_DIR,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    WS_PORT: process.env.WS_PORT,
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_WS_URL: process.env.NEXT_PUBLIC_WS_URL,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
  },
  emptyStringAsUndefined: true,
  skipValidation: process.env.SKIP_ENV_VALIDATION === "1",
});
